import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.scss";
import Link from "next/link";
import StoreProvider from "./StoreProvider";
const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubik.variable}`}>
        <StoreProvider>
          <div className="container">
            <header className="header">
              <Link className="link" href="/about">About</Link>
            <Link className="link" href="/components">Components</Link>
            <Link className="link" href="/create">Create</Link>
          </header>
            {children}
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
